"""
Cadencia — Seed 50 Sellers across 10 Industries.

Registers 50 seller enterprises via the REST API, creates capability profiles
and catalogue items. Embeddings are generated by the backend on profile creation.

Usage:
    cd backend/
    API_URL=http://localhost:8000 python scripts/seed_50_sellers.py

    # Against production:
    API_URL=https://cadencia-magic-wallet.duckdns.org python scripts/seed_50_sellers.py

Password for all seeded users: Demo@Cadencia2026
"""

from __future__ import annotations

import asyncio
import csv
import os
import sys
from pathlib import Path

import httpx

API_URL = os.environ.get("API_URL", "http://localhost:8000")
PASSWORD = "Demo@Cadencia2026"

# GST state code → state name mapping (for address)
STATE_CODES = {
    "02": "Himachal Pradesh", "03": "Punjab", "05": "Uttarakhand",
    "06": "Haryana", "07": "Delhi", "08": "Rajasthan", "09": "Uttar Pradesh",
    "20": "Jharkhand", "21": "Odisha", "22": "Chhattisgarh",
    "23": "Madhya Pradesh", "24": "Gujarat", "25": "Daman and Diu",
    "26": "Dadra and Nagar Haveli", "27": "Maharashtra", "29": "Karnataka",
    "30": "Goa", "32": "Kerala", "33": "Tamil Nadu", "36": "Telangana",
    "37": "Andhra Pradesh",
}


def _load_sellers() -> list[dict]:
    """Load sellers from CSV."""
    csv_path = Path(__file__).parent / "sellers_50.csv"
    sellers = []
    with open(csv_path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            sellers.append(row)
    return sellers


async def _check_health(client: httpx.AsyncClient) -> bool:
    try:
        r = await client.get(f"{API_URL}/health")
        return r.status_code == 200
    except httpx.ConnectError:
        return False


async def _register_seller(client: httpx.AsyncClient, seller: dict) -> dict | None:
    """Register enterprise + user via /v1/auth/register. Returns token or None."""
    commodities = [c.strip() for c in seller["commodities"].split(",")]
    certifications = [c.strip() for c in seller["certifications"].split(",")]

    payload = {
        "enterprise": {
            "legal_name": seller["company_name"],
            "pan": seller["pan"],
            "gstin": seller["gstin"],
            "trade_role": "SELLER",
            "commodities": commodities,
            "min_order_value": float(seller["min_order_value"]),
            "max_order_value": float(seller["max_order_value"]),
            "industry_vertical": seller["industry"],
            "geography": "PAN_INDIA",
            "facility_type": seller["facility_type"],
            "years_in_operation": int(seller["years_in_operation"]),
            "annual_turnover_inr": float(seller["annual_turnover_inr"]),
            "quality_certifications": certifications,
            "test_certificate_available": True,
            "third_party_inspection_allowed": True,
            "address": {
                "address_type": "FACILITY",
                "address_line1": f"Industrial Area, {seller['city']}",
                "city": seller["city"],
                "state": seller["state"],
                "pincode": seller["pincode"],
            },
        },
        "user": {
            "email": seller["email"],
            "password": PASSWORD,
            "full_name": f"Admin {seller['company_name'].split()[0]}",
            "role": "ADMIN",
        },
    }

    r = await client.post(f"{API_URL}/v1/auth/register", json=payload)
    if r.status_code in (200, 201):
        token = r.json().get("data", {}).get("access_token", "")
        return {"token": token, "new": True}
    elif r.status_code == 409:
        # Already exists — try login
        login_r = await client.post(f"{API_URL}/v1/auth/login", json={
            "email": seller["email"],
            "password": PASSWORD,
        })
        if login_r.status_code == 200:
            token = login_r.json().get("data", {}).get("access_token", "")
            return {"token": token, "new": False}
    return None


async def _create_capability_profile(
    client: httpx.AsyncClient, token: str, seller: dict
) -> bool:
    """Create seller capability profile via PUT /v1/marketplace/capability-profile."""
    commodities = [c.strip() for c in seller["commodities"].split(",")]

    payload = {
        "industry": seller["industry"],
        "products": commodities,
        "geographies": ["PAN_INDIA"],
        "min_order_value": float(seller["min_order_value"]),
        "max_order_value": float(seller["max_order_value"]),
        "description": seller["profile_text"],
    }

    try:
        r = await client.put(
            f"{API_URL}/v1/marketplace/capability-profile",
            json=payload,
            headers={"Authorization": f"Bearer {token}"},
            timeout=60.0,
        )
        return r.status_code in (200, 201)
    except Exception:
        return False


async def _create_catalogue_item(
    client: httpx.AsyncClient, token: str, seller: dict
) -> bool:
    """Create a catalogue item via /v1/marketplace/catalogue."""
    hsn_codes = [h.strip() for h in seller["hsn_codes"].split(",")]

    payload = {
        "product_name": seller["products"],
        "hsn_code": hsn_codes[0],
        "product_category": seller["product_category"],
        "grade": seller["grade"],
        "unit": seller["unit"],
        "price_per_unit_inr": float(seller["price_per_unit_inr"]),
        "moq": float(seller["moq"]),
        "max_order_qty": float(seller["max_order_qty"]),
        "lead_time_days": int(seller["lead_time_days"]),
        "specification_text": seller["profile_text"],
        "floor_price_inr": float(seller["floor_price_inr"]),
        "max_discount_pct": float(seller["max_discount_pct"]),
        "negotiation_enabled": True,
        "certifications": [c.strip() for c in seller["certifications"].split(",")],
    }

    try:
        r = await client.post(
            f"{API_URL}/v1/marketplace/catalogue",
            json=payload,
            headers={"Authorization": f"Bearer {token}"},
            timeout=60.0,
        )
        return r.status_code in (200, 201)
    except Exception:
        return False


async def main() -> None:
    sellers = _load_sellers()
    print("=" * 70)
    print(f"Cadencia — Seed 50 Sellers ({len(sellers)} loaded from CSV)")
    print(f"API: {API_URL}")
    print("=" * 70)

    async with httpx.AsyncClient(timeout=60.0) as client:
        # Health check
        if not await _check_health(client):
            print(f"[FAIL] API not reachable at {API_URL}")
            sys.exit(1)
        print("[OK] API healthy\n")

        stats = {"registered": 0, "existed": 0, "failed": 0, "profiles": 0, "catalogue": 0}

        for i, seller in enumerate(sellers, 1):
            name = seller["company_name"]
            industry = seller["industry"]

            # 1. Register enterprise + user
            result = await _register_seller(client, seller)
            if result is None:
                print(f"  [{i:2d}/50] FAIL  {name}")
                stats["failed"] += 1
                continue

            token = result["token"]
            if result["new"]:
                stats["registered"] += 1
                label = "NEW"
            else:
                stats["existed"] += 1
                label = "EXIST"

            # 2. Create capability profile
            profile_ok = await _create_capability_profile(client, token, seller)
            if profile_ok:
                stats["profiles"] += 1

            # 3. Create catalogue item
            cat_ok = await _create_catalogue_item(client, token, seller)
            if cat_ok:
                stats["catalogue"] += 1

            p_icon = "P" if profile_ok else "-"
            c_icon = "C" if cat_ok else "-"
            print(f"  [{i:2d}/50] {label:5s} [{p_icon}{c_icon}] {name:<45s} ({industry})")

            # Small delay to avoid overwhelming the API
            await asyncio.sleep(0.3)

        # Summary
        print("\n" + "=" * 70)
        print("SEED COMPLETE")
        print("=" * 70)
        print(f"  Registered:  {stats['registered']}")
        print(f"  Existed:     {stats['existed']}")
        print(f"  Failed:      {stats['failed']}")
        print(f"  Profiles:    {stats['profiles']}")
        print(f"  Catalogue:   {stats['catalogue']}")
        print(f"\n  Password:    {PASSWORD}")
        print(f"  Industries:  10")
        print(f"  Total:       {stats['registered'] + stats['existed']} sellers")

        # Print industry breakdown
        industries = {}
        for s in sellers:
            ind = s["industry"]
            industries[ind] = industries.get(ind, 0) + 1
        print("\n  Industry Breakdown:")
        for ind, count in industries.items():
            print(f"    {ind:<35s} {count} sellers")


if __name__ == "__main__":
    asyncio.run(main())
